"""Tests for the core data models and their adapters."""

from __future__ import annotations

import numpy as np
import pytest

from actuator_viz import Actuator, ActuatorConfig, CoordinateFrame


def test_zero_axis_is_rejected():
    with pytest.raises(ValueError):
        Actuator(id=0, position=(0, 0, 0), axis=(0, 0, 0))


def test_wrong_length_position_is_rejected():
    with pytest.raises(ValueError):
        Actuator(id=0, position=(0, 0), axis=(0, 0, 1))


def test_name_is_autogenerated_when_missing():
    a = Actuator(id=3, position=(0, 0, 0), axis=(0, 0, 1))
    assert a.name == "Actuator_3"


def test_axis_normalized_is_unit_length():
    a = Actuator(id=0, position=(0, 0, 0), axis=(0, 0, 5))
    np.testing.assert_allclose(a.axis_normalized, [0, 0, 1])


def test_duplicate_ids_are_rejected():
    with pytest.raises(ValueError):
        ActuatorConfig(actuators=[
            Actuator(id=0, position=(0, 0, 0), axis=(0, 0, 1)),
            Actuator(id=0, position=(1, 0, 0), axis=(0, 0, 1)),
        ])


def test_frame_string_is_coerced_to_enum():
    config = ActuatorConfig(
        actuators=[Actuator(id=0, position=(0, 0, 0), axis=(0, 0, 1))],
        frame="NED",
    )
    assert config.frame is CoordinateFrame.NED


def test_get_actuator_by_id_and_name():
    a = Actuator(id=5, name="thruster-a", position=(0, 0, 0), axis=(0, 0, 1))
    config = ActuatorConfig(actuators=[a])
    assert config.get_actuator(5) is a
    assert config.get_actuator("thruster-a") is a
    assert config.get_actuator(99) is None


def test_rotor_list_roundtrip_preserves_geometry():
    config = ActuatorConfig(actuators=[
        Actuator(id=0, position=(0.1, 0.2, 0.3), axis=(0, 0, 1), coefficient=1.5),
        Actuator(id=1, position=(-0.1, 0.0, 0.2), axis=(1, 0, 0), moment_ratio=0.2),
    ])
    rotors = config.to_rotor_list()
    rebuilt = ActuatorConfig.from_rotor_list(rotors)

    for original, copy in zip(config.actuators, rebuilt.actuators):
        np.testing.assert_allclose(copy.position, original.position)
        np.testing.assert_allclose(copy.axis, original.axis)
        assert copy.coefficient == original.coefficient
        assert copy.moment_ratio == original.moment_ratio
